### ISSUE TITLE
Place Order Returns Error

### ISSUE THREAD

**Issue by moshiurrafialvi** [JaberHPranto/Plant-Land#4]
![Screenshot_15](https://user-images.githubusercontent.com/62988289/125016298-ecf10e80-e092-11eb-9e9d-944db573f3dd.png)

**Comment by moshiurrafialvi** [comment]
@JaberHPranto

**Comment by JaberHPranto** [comment]
Ok....I'll check it

**Comment by JaberHPranto** [comment]
Place order now works properly !!!
